# Generated by Django 4.2.4 on 2023-08-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('style', models.CharField(choices=[('P', 'physique'), ('M', 'morale')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=15, unique=True)),
            ],
        ),
    ]
