# Generated by Django 4.2.4 on 2023-08-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_phone_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
