# Generated by Django 4.2.4 on 2023-08-07 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_remove_customer_phone_customer_phone_number'),
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id_nature', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id_complain', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('attached_file', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('id_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager.account_manager')),
                ('id_nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain.nature')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain.status')),
            ],
        ),
    ]
