# Generated by Django 4.2.4 on 2023-08-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='id_complain',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nature',
            name='id_nature',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='id_status',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
