# Generated by Django 4.2.4 on 2023-08-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AddField(
            model_name='role',
            name='id_role',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_manager',
            name='id_manager',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
